[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
serde-graphql-input = { path = "crates/serde-graphql-input" }

anyhow = { version = "1.0.82" }
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
